{{- if not .Values.adx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: akernel-etcd
  namespace: {{ .Release.Namespace }}
  labels:
    app: etcd
    {{- with .Values.etcd.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: client
      port: 2379
      protocol: TCP
      targetPort: 2379
    - name: peer
      port: 2378
      protocol: TCP
      targetPort: 2378
  selector:
    app: etcd
  sessionAffinity: None
{{- end }}
