{{- if not .Values.adx.enabled }}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core.litebusSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: akernel-master
type: Opaque
stringData:
  litebus-data-key: {{ include "core.litebusDataKey" . | quote }}
{{- end }}
{{- end }}
