{{- if not .Values.adx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: akernel-master
  namespace: {{ .Release.Namespace }}
  labels:
    app: akernel-master
    {{- with .Values.master.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.master.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if eq (default "ClusterIP" .Values.master.service.type) "ClusterIP" }}
  clusterIP: None
  {{- end }}
  type: {{ default "ClusterIP" .Values.master.service.type }}
  {{- if and (eq (default "ClusterIP" .Values.master.service.type) "LoadBalancer") .Values.master.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.master.service.loadBalancerIP | quote }}
  {{- end }}
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: global-sched
      port: 22770
      targetPort: 22770
      protocol: TCP
    - name: metaservice
      port: 31111
      targetPort: 31111
      protocol: TCP
    - name: iam-server
      port: 31112
      targetPort: 31112
      protocol: TCP
  selector:
    app: akernel-master
  sessionAffinity: None
{{- end }}
